<?php

use CRM_Committees_ExtensionUtil as E;

return [
  [
    'name' => 'SavedSearch_CommitteeListing',
    'entity' => 'SavedSearch',
    'cleanup' => 'always',
    'update' => 'unmodified',
    'params' => [
      'version' => 4,
      'values' => [
        'name' => 'CommitteeListing',
        'label' => E::ts('Committees'),
        'form_values' => null,
        'mapping_id' => null,
        'search_custom_id' => null,
        'api_entity' => 'Committee',
        'api_params' => [
          'version' => 4,
          'select' => [
            'id',
            'name',
            'summary',
            'activities',
            'hl_community',
            'is_active',
          ],
          'orderBy' => [],
          'where' => [],
          'groupBy' => [],
          'join' => [],
          'having' => [],
        ],
        'expires_date' => null,
        'description' => null,
      ],
      'match' => [
        'name',
      ],
    ],
  ],
  [
    'name' => 'SavedSearch_CommitteeListing_SearchDisplay_Committee_Listing',
    'entity' => 'SearchDisplay',
    'cleanup' => 'always',
    'update' => 'unmodified',
    'params' => [
      'version' => 4,
      'values' => [
        'name' => 'Committee_Listing',
        'label' => E::ts('Committee Listing'),
        'saved_search_id.name' => 'CommitteeListing',
        'type' => 'table',
        'settings' => [
          'description' => null,
          'sort' => [],
          'limit' => 50,
          'pager' => [],
          'placeholder' => 5,
          'columns' => [
            [
              'type' => 'field',
              'key' => 'id',
              'dataType' => 'Integer',
              'label' => E::ts('ID'),
              'sortable' => true,
            ],
            [
              'type' => 'field',
              'key' => 'name',
              'dataType' => 'String',
              'label' => E::ts('Title'),
              'sortable' => true,
            ],
            [
              'type' => 'field',
              'key' => 'hl_community',
              'dataType' => 'String',
              'label' => E::ts('HL Community'),
              'sortable' => true,
            ],
            [
              'type' => 'field',
              'key' => 'is_active',
              'dataType' => 'Boolean',
              'label' => E::ts('Committee Is Active'),
              'sortable' => true,
            ],
            [
              'size' => 'btn-xs',
              'links' => [
                [
                    'task' => 'disable',
                    'entity' => 'Committee',
                    'join' => '',
                    'target' => 'crm-popup',
                    'icon' => 'fa-toggle-off',
                    'text' => E::ts('Disable'),
                    'style' => 'default',
                    'path' => '',
                    'action' => '',
                    'condition' => [
                        'is_active',
                        '=',
                        true,
                    ],
                ],
                [
                    'task' => 'enable',
                    'entity' => 'Committee',
                    'join' => '',
                    'target' => 'crm-popup',
                    'icon' => 'fa-toggle-on',
                    'text' => E::ts('Enable'),
                    'style' => 'default',
                    'path' => '',
                    'action' => '',
                    'condition' => [
                        'is_active',
                        '=',
                        false,
                    ],
                ],
                [
                    'task' => '',
                    'entity' => 'Committee',
                    'join' => '',
                    'target' => 'crm-popup',
                    'icon' => 'fa-external-link',
                    'text' => E::ts('Edit'),
                    'style' => 'default',
                    'path' => 'civicrm/committee/manage#?Committee=[id]',
                    'action' => '',
                    'condition' => [],
                ],
                [
                    'task' => 'delete',
                    'entity' => 'Committee',
                    'join' => '',
                    'target' => 'crm-popup',
                    'icon' => 'fa-trash',
                    'text' => E::ts('Delete'),
                    'style' => 'danger',
                    'path' => '',
                    'action' => '',
                    'condition' => [],
                ],
              ],
              'type' => 'buttons',
              'alignment' => 'text-right',
            ],
          ],
          'actions' => true,
          'classes' => [
            'table',
            'table-striped',
          ],
        ],
        'acl_bypass' => false,
      ],
      'match' => [
        'name',
        'saved_search_id',
      ],
    ],
  ],
];
