<?php

use CRM_Committees_ExtensionUtil as E;

return [
  [
    'name' => 'SavedSearch_CommitteeRolesDashboard',
    'entity' => 'SavedSearch',
    'cleanup' => 'always',
    'update' => 'unmodified',
    'params' => [
      'version' => 4,
      'values' => [
        'name' => 'CommitteeRolesDashboard',
        'label' => E::ts('Committee Roles'),
        'form_values' => null,
        'mapping_id' => null,
        'search_custom_id' => null,
        'api_entity' => 'CommitteeRole',
        'api_params' => [
          'version' => 4,
          'select' => [
            'id',
            'name',
            'is_active',
          ],
          'orderBy' => [],
          'where' => [],
          'groupBy' => [],
          'join' => [],
          'having' => [],
        ],
        'expires_date' => null,
        'description' => null,
      ],
      'match' => [
        'name',
      ],
    ],
  ],
  [
    'name' => 'SavedSearch_CommitteeRolesDashboard_SearchDisplay_Committee_Roles_Table',
    'entity' => 'SearchDisplay',
    'cleanup' => 'always',
    'update' => 'unmodified',
    'params' => [
      'version' => 4,
      'values' => [
        'name' => 'Committee_Roles_Table',
        'label' => E::ts('Committee Roles Dashboard'),
        'saved_search_id.name' => 'CommitteeRolesDashboard',
        'type' => 'table',
        'settings' => [
          'description' => null,
          'sort' => [],
          'limit' => 50,
          'pager' => [],
          'placeholder' => 5,
          'columns' => [
            [
              'type' => 'field',
              'key' => 'id',
              'dataType' => 'Integer',
              'label' => E::ts('ID'),
              'sortable' => true,
            ],
            [
              'type' => 'field',
              'key' => 'name',
              'dataType' => 'String',
              'label' => E::ts('Title'),
              'sortable' => true,
            ],
            [
              'type' => 'field',
              'key' => 'is_active',
              'dataType' => 'Boolean',
              'label' => E::ts('Role Is Active'),
              'sortable' => true,
            ],
            [
              'size' => 'btn-xs',
              'links' => [
                [
                        'task' => 'disable',
                        'entity' => 'CommitteeRole',
                        'join' => '',
                        'target' => 'crm-popup',
                        'icon' => 'fa-toggle-off',
                        'text' => E::ts('Disable'),
                        'style' => 'default',
                        'path' => '',
                        'action' => '',
                        'condition' => [
                            'is_active',
                            '=',
                            true,
                        ],
                    ],
                    [
                        'task' => 'enable',
                        'entity' => 'CommitteeRole',
                        'join' => '',
                        'target' => 'crm-popup',
                        'icon' => 'fa-toggle-on',
                        'text' => E::ts('Enable'),
                        'style' => 'default',
                        'path' => '',
                        'action' => '',
                        'condition' => [
                            'is_active',
                            '=',
                            false,
                        ],
                    ],
                    [
                        'task' => '',
                        'entity' => 'CommitteeRole',
                        'join' => '',
                        'target' => 'crm-popup',
                        'icon' => 'fa-external-link',
                        'text' => E::ts('Edit'),
                        'style' => 'default',
                        'path' => 'civicrm/committee/role/manage#?CommitteeRole=[id]',
                        'action' => '',
                        'condition' => [],
                    ],
                    [
                        'task' => 'delete',
                        'entity' => 'CommitteeRole',
                        'join' => '',
                        'target' => 'crm-popup',
                        'icon' => 'fa-trash',
                        'text' => E::ts('Delete'),
                        'style' => 'danger',
                        'path' => '',
                        'action' => '',
                        'condition' => [],
                    ],
              ],
              'type' => 'buttons',
              'alignment' => 'text-right',
            ],
          ],
          'actions' => true,
          'classes' => [
            'table',
            'table-striped',
          ],
        ],
        'acl_bypass' => false,
      ],
      'match' => [
        'name',
        'saved_search_id',
      ],
    ],
  ],
];
