<?php
return [
	[
		'name' => 'SavedSearch_Committee_Appointments',
		'entity' => 'SavedSearch',
		'cleanup' => 'always',
		'update' => 'unmodified',
		'params' => [
		'version' => 4,
		'values' => [
			'name' => 'Committee_Appointments',
			'label' => 'Committee Appointments',
			'form_values' => NULL,
			'mapping_id' => NULL,
			'search_custom_id' => NULL,
			'api_entity' => 'CommitteeAppointment',
			'api_params' => [
			'version' => 4,
			'select' => [
				'id',
				'CommitteeAppointment_Contact_contact_id_01.display_name',
				'CommitteeAppointment_Committee_committee_id_01.name',
				'CommitteeAppointment_CommitteeRole_committee_role_id_01.name',
				'start_date',
				'end_date',
				'is_active',
			],
			'orderBy' => [],
			'where' => [],
			'groupBy' => [],
			'join' => [
				[
					'Committee AS CommitteeAppointment_Committee_committee_id_01',
					'INNER',
					[
						'committee_id',
						'=',
						'CommitteeAppointment_Committee_committee_id_01.id',
					],
					[
						'CommitteeAppointment_Committee_committee_id_01.is_active',
						'=',
						TRUE,
					],
				],
				[
					'Contact AS CommitteeAppointment_Contact_contact_id_01',
					'INNER',
					[
						'contact_id',
						'=',
						'CommitteeAppointment_Contact_contact_id_01.id',
					],
				],
				[
					'CommitteeRole AS CommitteeAppointment_CommitteeRole_committee_role_id_01',
					'INNER',
					[
						'committee_role_id',
						'=',
						'CommitteeAppointment_CommitteeRole_committee_role_id_01.id',
					],
					[
						'CommitteeAppointment_CommitteeRole_committee_role_id_01.is_active',
						'=',
						TRUE,
					],
				],
			],
			'having' => [],
			],
			'expires_date' => NULL,
			'description' => NULL,
		],
		],
	],
	[
		'name' => 'SavedSearch_Committee_Appointments_SearchDisplay_Committee_Appointments_Table',
		'entity' => 'SearchDisplay',
		'cleanup' => 'always',
		'update' => 'unmodified',
		'params' => [
		'version' => 4,
		'values' => [
			'name' => 'Committee_Appointments_Table',
			'label' => 'Committee Appointments Table',
			'saved_search_id.name' => 'Committee_Appointments',
			'type' => 'table',
			'settings' => [
			'description' => NULL,
			'sort' => [],
			'limit' => 50,
			'pager' => [],
			'placeholder' => 5,
			'columns' => [
				[
					'type' => 'field',
					'key' => 'id',
					'dataType' => 'Integer',
					'label' => 'ID',
					'sortable' => TRUE,
				],
				[
					'type' => 'field',
					'key' => 'CommitteeAppointment_Contact_contact_id_01.display_name',
					'dataType' => 'String',
					'label' => 'Contact Name',
					'sortable' => TRUE,
					'link' => [
						'path' => '',
						'entity' =>'Contact',
						'action' => 'view',
						'join' => 'CommitteeAppointment_Contact_contact_id_01',
						'target' => '_blank'
					],
					'title' => 'View Contact'
				],
				[
					'type' => 'field',
					'key' => 'CommitteeAppointment_Committee_committee_id_01.name',
					'dataType' => 'String',
					'label' => 'Committee',
					'sortable' => TRUE,
				],
				[
					'type' => 'field',
					'key' => 'CommitteeAppointment_CommitteeRole_committee_role_id_01.name',
					'dataType' => 'String',
					'label' => 'Role',
					'sortable' => TRUE,
				],
				[
					'type' => 'field',
					'key' => 'start_date',
					'dataType' => 'Date',
					'label' => 'Start Date',
					'sortable' => TRUE,
				],
				[
					'type' => 'field',
					'key' => 'end_date',
					'dataType' => 'Date',
					'label' => 'End Date',
					'sortable' => TRUE,
				],
				[
					'type' => 'field',
					'key' => 'is_active',
					'dataType' => 'Boolean',
					'label' => 'Is Active',
					'sortable' => TRUE,
				],
				[
					'size' => 'btn-xs',
					'links' => [
						[
							'path' => 'civicrm/committee/appointment/manage#?CommitteeAppointment=[id]',
							'icon' => 'fa-external-link',
							'text' => 'Edit',
							'style' => 'default',
							'condition' => [],
							'entity' => '',
							'action' => '',
							'join' => '',
							'target' => 'crm-popup',
						],
					],
					'type' => 'buttons',
					'alignment' => 'text-right',
				],
			],
			'actions' => TRUE,
			'classes' => [
				'table',
				'table-striped',
			],
			],
			'acl_bypass' => FALSE,
		],
		],
	],
	[
		'name' => 'SavedSearch_Committee_Appointments_SearchDisplay_Contact_Committee_Appointments_Table',
		'entity' => 'SearchDisplay',
		'cleanup' => 'always',
		'update' => 'unmodified',
		'params' => [
		'version' => 4,
		'values' => [
			'name' => 'Contact_Committee_Appointments',
			'label' => 'Contact Committee Appointments',
			'saved_search_id.name' => 'Committee_Appointments',
			'type' => 'table',
			'settings' => [
			'description' => NULL,
			'sort' => [],
			'limit' => 50,
			'pager' => [],
			'placeholder' => 5,
			'columns' => [
				[
				'type' => 'field',
				'key' => 'CommitteeAppointment_Committee_committee_id_01.name',
				'dataType' => 'String',
				'label' => 'Committee',
				'sortable' => TRUE,
				],
				[
				'type' => 'field',
				'key' => 'CommitteeAppointment_CommitteeRole_committee_role_id_01.name',
				'dataType' => 'String',
				'label' => 'Role',
				'sortable' => TRUE,
				],
				[
				'type' => 'field',
				'key' => 'start_date',
				'dataType' => 'Date',
				'label' => 'Start Date',
				'sortable' => TRUE,
				],
				[
				'type' => 'field',
				'key' => 'end_date',
				'dataType' => 'Date',
				'label' => 'End Date',
				'sortable' => TRUE,
				],
				[
				'type' => 'field',
				'key' => 'is_active',
				'dataType' => 'Boolean',
				'label' => 'Is Active',
				'sortable' => TRUE,
				],
				[
					'size' => 'btn-xs',
					'links' => [
						[
							'path' => 'civicrm/committee/appointment/manage#?CommitteeAppointment=[id]',
							'icon' => 'fa-external-link',
							'text' => 'Edit',
							'style' => 'default',
							'condition' => [],
							'entity' => '',
							'action' => '',
							'join' => '',
							'target' => 'crm-popup',
						],
					],
					'type' => 'buttons',
					'alignment' => 'text-right',
				],
			],
			'actions' => TRUE,
			'classes' => [
				'table',
				'table-striped',
			],
			],
			'acl_bypass' => FALSE,
		],
		],
	],
];
