<?php

use CRM_Committees_ExtensionUtil as E;

return [
  [
    'name' => 'SavedSearch_Committee_Appointments',
    'entity' => 'SavedSearch',
    'cleanup' => 'always',
    'update' => 'unmodified',
    'params' => [
      'version' => 4,
      'values' => [
        'name' => 'Committee_Appointments',
        'label' => E::ts('Committee Appointments'),
        'api_entity' => 'CommitteeAppointment',
        'api_params' => [
          'version' => 4,
          'select' => [
            'id',
            'CommitteeAppointment_Contact_contact_id_01.display_name',
            'CommitteeAppointment_Committee_committee_id_01.name',
            'CommitteeAppointment_CommitteeRole_committee_role_id_01.name',
            'start_date',
            'end_date',
            'eligibility_end_date',
            'is_active',
            'CommitteeAppointment_Contact_contact_id_01_Contact_Membership_contact_id_01.status_id:label',
          ],
          'orderBy' => [],
          'where' => [],
          'groupBy' => [],
          'join' => [
            [
              'Committee AS CommitteeAppointment_Committee_committee_id_01',
              'INNER',
              [
                'committee_id',
                '=',
                'CommitteeAppointment_Committee_committee_id_01.id',
              ],
              [
                'CommitteeAppointment_Committee_committee_id_01.is_active',
                '=',
                TRUE,
              ],
            ],
            [
              'Contact AS CommitteeAppointment_Contact_contact_id_01',
              'INNER',
              [
                'contact_id',
                '=',
                'CommitteeAppointment_Contact_contact_id_01.id',
              ],
              [
                "CommitteeAppointment_Contact_contact_id_01.contact_type:name",
                "=",
                "'Individual'"
              ]
            ],
            [
              'CommitteeRole AS CommitteeAppointment_CommitteeRole_committee_role_id_01',
              'INNER',
              [
                'committee_role_id',
                '=',
                'CommitteeAppointment_CommitteeRole_committee_role_id_01.id',
              ],
              [
                'CommitteeAppointment_CommitteeRole_committee_role_id_01.is_active',
                '=',
                TRUE,
              ],
            ],
            [
              'Membership AS CommitteeAppointment_Contact_contact_id_01_Contact_Membership_contact_id_01',
              'LEFT',
              [
                'CommitteeAppointment_Contact_contact_id_01.id',
                '=',
                'CommitteeAppointment_Contact_contact_id_01_Contact_Membership_contact_id_01.contact_id',
              ],
              [
                'CommitteeAppointment_Contact_contact_id_01_Contact_Membership_contact_id_01.membership_type_id:name',
                'IN',
                [
                  'Active',
                  'Emeritus',
                  'Junior',
                  'Central Office',
                ],
              ],
            ],
          ],
          'having' => [],
        ],
      ],
      'match' => [
        'name',
      ],
    ],
  ],
  [
    'name' => 'SavedSearch_Committee_Appointments_SearchDisplay_Committee_Appointments_Table',
    'entity' => 'SearchDisplay',
    'cleanup' => 'always',
    'update' => 'unmodified',
    'params' => [
      'version' => 4,
      'values' => [
        'name' => 'Committee_Appointments_Table',
        'label' => E::ts('Committee Appointments Table'),
        'saved_search_id.name' => 'Committee_Appointments',
        'type' => 'table',
        'settings' => [
          'description' => NULL,
          'sort' => [],
          'limit' => 50,
          'pager' => [],
          'placeholder' => 5,
          'columns' => [
            [
              'type' => 'field',
              'key' => 'id',
              'dataType' => 'Integer',
              'label' => E::ts('ID'),
              'sortable' => TRUE,
            ],
            [
              'type' => 'field',
              'key' => 'CommitteeAppointment_Contact_contact_id_01.display_name',
              'dataType' => 'String',
              'label' => E::ts('Contact Name'),
              'sortable' => TRUE,
              'link' => [
                'path' => '',
                'entity' => 'Contact',
                'action' => 'view',
                'join' => 'CommitteeAppointment_Contact_contact_id_01',
                'target' => '_blank',
              ],
              'title' => E::ts('View Contact'),
            ],
            [
              'type' => 'field',
              'key' => 'CommitteeAppointment_Committee_committee_id_01.name',
              'dataType' => 'String',
              'label' => E::ts('Committee'),
              'sortable' => TRUE,
            ],
            [
              'type' => 'field',
              'key' => 'CommitteeAppointment_CommitteeRole_committee_role_id_01.name',
              'dataType' => 'String',
              'label' => E::ts('Role'),
              'sortable' => TRUE,
            ],
            [
              'type' => 'field',
              'key' => 'start_date',
              'dataType' => 'Date',
              'label' => E::ts('Appointment Start Date'),
              'sortable' => TRUE,
            ],
            [
              'type' => 'field',
              'key' => 'end_date',
              'dataType' => 'Date',
              'label' => E::ts('Annual Appointment End Date'),
              'sortable' => TRUE,
            ],
            [
              'type' => 'field',
              'key' => 'eligibility_end_date',
              'dataType' => 'Date',
              'label' => E::ts('Eligibility End Date'),
              'sortable' => TRUE,
            ],
            [
              'type' => 'field',
              'key' => 'is_active',
              'dataType' => 'Boolean',
              'label' => E::ts('Is Active'),
              'sortable' => TRUE,
            ],
            [
              'type' => 'field',
              'key' => 'CommitteeAppointment_Contact_contact_id_01_Contact_Membership_contact_id_01.status_id:label',
              'dataType' => 'Integer',
              'label' => E::ts('Membership Status'),
              'sortable' => TRUE,
            ],
            [
              'size' => 'btn-xs',
              'links' => [
                [
                  'task' => 'disable',
                  'entity' => 'CommitteeAppointment',
                  'join' => '',
                  'target' => 'crm-popup',
                  'icon' => 'fa-toggle-off',
                  'text' => E::ts('Disable'),
                  'style' => 'default',
                  'path' => '',
                  'action' => '',
                  'condition' => [
                    'is_active',
                    '=',
                    TRUE,
                  ],
                ],
                [
                  'task' => 'enable',
                  'entity' => 'CommitteeAppointment',
                  'join' => '',
                  'target' => 'crm-popup',
                  'icon' => 'fa-toggle-on',
                  'text' => E::ts('Enable'),
                  'style' => 'default',
                  'path' => '',
                  'action' => '',
                  'condition' => [
                    'is_active',
                    '=',
                    FALSE,
                  ],
                ],
                [
                  'entity' => 'CommitteeAppointment',
                  'task' => '',
                  'join' => '',
                  'target' => 'crm-popup',
                  'icon' => 'fa-external-link',
                  'text' => E::ts('Edit'),
                  'style' => 'default',
                  'path' => 'civicrm/committee/appointment/manage#?CommitteeAppointment=[id]',
                  'action' => '',
                  'condition' => [],
                ],
                [
                  'task' => 'delete',
                  'entity' => 'CommitteeAppointment',
                  'join' => '',
                  'target' => 'crm-popup',
                  'icon' => 'fa-trash',
                  'text' => E::ts('Delete'),
                  'style' => 'danger',
                  'path' => '',
                  'action' => '',
                  'condition' => [],
                ],
              ],
              'type' => 'buttons',
              'alignment' => 'text-right',
            ],
          ],
          'actions' => TRUE,
          'classes' => [
            'table',
            'table-striped',
          ],
        ],
      ],
      'match' => [
        'saved_search_id',
        'name',
      ],
    ],
  ],
  [
    'name' => 'SavedSearch_Committee_Appointments_SearchDisplay_Contact_Committee_Appointments_Table',
    'entity' => 'SearchDisplay',
    'cleanup' => 'always',
    'update' => 'unmodified',
    'params' => [
      'version' => 4,
      'values' => [
        'name' => 'Contact_Committee_Appointments',
        'label' => E::ts('Contact Committee Appointments'),
        'saved_search_id.name' => 'Committee_Appointments',
        'type' => 'table',
        'settings' => [
          'description' => NULL,
          'sort' => [],
          'limit' => 50,
          'pager' => [],
          'placeholder' => 5,
          'columns' => [
            [
              'type' => 'field',
              'key' => 'CommitteeAppointment_Committee_committee_id_01.name',
              'dataType' => 'String',
              'label' => E::ts('Committee'),
              'sortable' => TRUE,
            ],
            [
              'type' => 'field',
              'key' => 'CommitteeAppointment_CommitteeRole_committee_role_id_01.name',
              'dataType' => 'String',
              'label' => E::ts('Role'),
              'sortable' => TRUE,
            ],
            [
              'type' => 'field',
              'key' => 'start_date',
              'dataType' => 'Date',
              'label' => E::ts('Appointment Start Date'),
              'sortable' => TRUE,
            ],
            [
              'type' => 'field',
              'key' => 'end_date',
              'dataType' => 'Date',
              'label' => E::ts('Annual Appointment End Date'),
              'sortable' => TRUE,
            ],
            [
              'type' => 'field',
              'key' => 'eligibility_end_date',
              'dataType' => 'Date',
              'label' => E::ts('Eligibility End Date'),
              'sortable' => TRUE,
            ],
            [
              'type' => 'field',
              'key' => 'is_active',
              'dataType' => 'Boolean',
              'label' => E::ts('Is Active'),
              'sortable' => TRUE,
            ],
            [
              'size' => 'btn-xs',
              'links' => [
                [
                  'task' => 'disable',
                  'entity' => 'CommitteeAppointment',
                  'join' => '',
                  'target' => 'crm-popup',
                  'icon' => 'fa-toggle-off',
                  'text' => E::ts('Disable'),
                  'style' => 'default',
                  'path' => '',
                  'action' => '',
                  'condition' => [
                    'is_active',
                    '=',
                    TRUE,
                  ],
                ],
                [
                  'task' => 'enable',
                  'entity' => 'CommitteeAppointment',
                  'join' => '',
                  'target' => 'crm-popup',
                  'icon' => 'fa-toggle-on',
                  'text' => E::ts('Enable'),
                  'style' => 'default',
                  'path' => '',
                  'action' => '',
                  'condition' => [
                    'is_active',
                    '=',
                    FALSE,
                  ],
                ],
                [
                  'entity' => 'CommitteeAppointment',
                  'task' => 'edit',
                  'join' => '',
                  'target' => 'crm-popup',
                  'icon' => 'fa-external-link',
                  'text' => E::ts('Edit'),
                  'style' => 'default',
                  'path' => '',
                  'action' => '',
                  'condition' => [],
                ],
                [
                  'task' => 'delete',
                  'entity' => 'CommitteeAppointment',
                  'join' => '',
                  'target' => 'crm-popup',
                  'icon' => 'fa-trash',
                  'text' => E::ts('Delete'),
                  'style' => 'danger',
                  'path' => '',
                  'action' => '',
                  'condition' => [],
                ],
              ],
              'type' => 'buttons',
              'alignment' => 'text-right',
            ],
          ],
          'actions' => TRUE,
          'classes' => [
            'table',
            'table-striped',
          ],
        ],
      ],
      'match' => [
        'saved_search_id',
        'name',
      ],
    ],
  ],
  [
    'name' => 'SavedSearch_Profile_Committee_Appointments',
    'entity' => 'SavedSearch',
    'cleanup' => 'always',
    'update' => 'unmodified',
    'params' => [
      'version' => 4,
      'values' => [
        'name' => 'Profile_Committee_Appointments',
        'label' => 'Profile Committee Appointments',
        'form_values' => NULL,
        'mapping_id' => NULL,
        'search_custom_id' => NULL,
        'api_entity' => 'CommitteeAppointment',
        'api_params' => [
          'version' => 4,
          'select' => [
            'id',
            'CommitteeAppointment_Contact_contact_id_01.display_name',
            'CommitteeAppointment_Committee_committee_id_01.name',
            'CommitteeAppointment_CommitteeRole_committee_role_id_01.name',
            'start_date',
            'end_date',
            'eligibility_end_date',
            'is_active',
          ],
          'orderBy' => [],
          'where' => [],
          'groupBy' => [],
          'join' => [
            [
              'Committee AS CommitteeAppointment_Committee_committee_id_01',
              'INNER',
              [
                'committee_id',
                '=',
                'CommitteeAppointment_Committee_committee_id_01.id',
              ],
              [
                'CommitteeAppointment_Committee_committee_id_01.is_active',
                '=',
                TRUE,
              ],
            ],
            [
              'Contact AS CommitteeAppointment_Contact_contact_id_01',
              'INNER',
              [
                'contact_id',
                '=',
                'CommitteeAppointment_Contact_contact_id_01.id',
              ],
              [
                'CommitteeAppointment_Contact_contact_id_01.id',
                '=',
                '"user_contact_id"',
              ],
            ],
            [
              'CommitteeRole AS CommitteeAppointment_CommitteeRole_committee_role_id_01',
              'INNER',
              [
                'committee_role_id',
                '=',
                'CommitteeAppointment_CommitteeRole_committee_role_id_01.id',
              ],
              [
                'CommitteeAppointment_CommitteeRole_committee_role_id_01.is_active',
                '=',
                TRUE,
              ],
            ],
          ],
          'having' => [],
        ],

      ],
      'match' => [
        'name',
      ],
    ],
  ],
  [
    'name' => 'SavedSearch_Profile_Committee_Appointments_SearchDisplay_Profile_Committee_Appointments',
    'entity' => 'SearchDisplay',
    'cleanup' => 'always',
    'update' => 'unmodified',
    'params' => [
      'version' => 4,
      'values' => [
        'name' => 'Profile_Committee_Appointment',
        'label' => 'Profile Committee Appointments',
        'saved_search_id.name' => 'Profile_Committee_Appointments',
        'type' => 'table',
        'settings' => [
          'description' => NULL,
          'sort' => [],
          'limit' => 50,
          'pager' => [],
          'placeholder' => 5,
          'columns' => [
            [
              'type' => 'field',
              'key' => 'CommitteeAppointment_Committee_committee_id_01.name',
              'dataType' => 'String',
              'label' => 'Committee',
              'sortable' => TRUE,
            ],
            [
              'type' => 'field',
              'key' => 'CommitteeAppointment_CommitteeRole_committee_role_id_01.name',
              'dataType' => 'String',
              'label' => 'Role',
              'sortable' => TRUE,
            ],
            [
              'type' => 'field',
              'key' => 'start_date',
              'dataType' => 'Date',
              'label' => 'Appointment Start Date',
              'sortable' => TRUE,
            ],
            [
              'type' => 'field',
              'key' => 'end_date',
              'dataType' => 'Date',
              'label' => 'Annual Appointment End Date',
              'sortable' => TRUE,
            ],
            [
              'type' => 'field',
              'key' => 'eligibility_end_date',
              'dataType' => 'Date',
              'label' => 'Eligibility End Date',
              'sortable' => TRUE,
            ],
          ],
          'actions' => FALSE,
          'classes' => [
            'table',
            'table-striped',
          ],
        ],
      ],
      'match' => [
        'saved_search_id',
        'name',
      ],
    ],
  ],
];
